# NumPy (Numerical Python) - Part 2

In [1]:
import numpy as np

In [4]:
list(range(5))  # range function generates range in integer value only

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [7]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
# numpy.arange() can generate range in float as well
np.arange(0.4,10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [12]:
np.arange(0.4, 10.4, 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [13]:
list(np.arange(0.4, 10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [16]:
np.linspace(1,5 , 20)  # linspace(1,5 , 20) is dividing the range 1 to 5 in 20 equal parts 

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [17]:
np.logspace(1,5 , 10)  # returns log range between 1 to 5 in 20 equal parts. by-default base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [18]:
np.logspace(1,5 , 10, base=2) 

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [31]:
np.zeros(5) # generates an array with all elements as zero

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [32]:
np.ones(5)  # generates an array with all elements as one

array([1., 1., 1., 1., 1.])

In [24]:
arr = np.ones((3,4))

In [25]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [27]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [33]:
np.empty((3,4))   # # generates an empty array with dummy elements

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [34]:
arr1 = np.eye(5)   # generates an identity array

In [35]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.identity(5)  # generates an identity array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
import pandas as pd

In [38]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

### Generating array using random function 

In [40]:
np.random.rand(2,3)  # returns array with any mean and std. deviation

array([[0.96384856, 0.20745852, 0.41019958],
       [0.74316564, 0.51846311, 0.29056265]])

In [43]:
np.random.randn(2,3)   # returns nomally distributed array with mean=0 and std.=1

array([[ 0.6819874 , -1.63008276, -0.21246667],
       [ 1.26323445, -0.95565181,  0.76302846]])

In [45]:
arr2 = np.random.randint(1,5 , (3,4))  # returns/generates an array with all integer values b/w 1 and 5 of shape 3x4

In [46]:
arr2

array([[2, 1, 4, 2],
       [1, 2, 1, 4],
       [4, 4, 1, 4]])

In [47]:
arr2.size

12

In [48]:
arr.shape

(3, 4)

In [50]:
arr2.reshape(6,2)  # we can reshape only by keeping size of the array same i.e we must use multiples of size vale to reshape an array

array([[2, 1],
       [4, 2],
       [1, 2],
       [1, 4],
       [4, 4],
       [1, 4]])

In [51]:
arr2.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [52]:
arr2.reshape(2,6)

array([[2, 1, 4, 2, 1, 2],
       [1, 4, 4, 4, 1, 4]])

In [53]:
arr2.reshape(4,3)

array([[2, 1, 4],
       [2, 1, 2],
       [1, 4, 4],
       [4, 1, 4]])

In [54]:
arr2.reshape(3,4)

array([[2, 1, 4, 2],
       [1, 2, 1, 4],
       [4, 4, 1, 4]])

In [55]:
arr2.reshape(4, -1)   # when provided any negative value the function automatically calulates the row /column

array([[2, 1, 4],
       [2, 1, 2],
       [1, 4, 4],
       [4, 1, 4]])

In [56]:
arr2.reshape(-1, 3)

array([[2, 1, 4],
       [2, 1, 2],
       [1, 4, 4],
       [4, 1, 4]])

In [57]:
arr2.reshape(4, -17570698)

array([[2, 1, 4],
       [2, 1, 2],
       [1, 4, 4],
       [4, 1, 4]])

In [58]:
arr2.reshape(2,2,3)

array([[[2, 1, 4],
        [2, 1, 2]],

       [[1, 4, 4],
        [4, 1, 4]]])

In [59]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[2]]],


         [[[1]]],


         [[[4]]]],



        [[[[2]]],


         [[[1]]],


         [[[2]]]]],




       [[[[[1]]],


         [[[4]]],


         [[[4]]]],



        [[[[4]]],


         [[[1]]],


         [[[4]]]]]])

In [60]:
arr1 = np.random.randint(1,10 , (5,6))

In [61]:
arr1

array([[4, 7, 1, 7, 7, 1],
       [5, 5, 5, 3, 2, 9],
       [2, 7, 1, 9, 3, 9],
       [9, 8, 5, 8, 7, 6],
       [7, 4, 3, 5, 4, 7]])

In [62]:
arr1 > 8

array([[False, False, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False, False,  True, False,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [63]:
arr1[arr1 > 8]

array([9, 9, 9, 9])

In [64]:
arr1

array([[4, 7, 1, 7, 7, 1],
       [5, 5, 5, 3, 2, 9],
       [2, 7, 1, 9, 3, 9],
       [9, 8, 5, 8, 7, 6],
       [7, 4, 3, 5, 4, 7]])

In [67]:
arr1[0 , [0,1]]

array([4, 7])

In [68]:
arr1[2:4, [2,3]]

array([[1, 9],
       [5, 8]])

In [74]:
arr1[4 , 3]

5

In [75]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [76]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [77]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [78]:
arr1 + arr2

array([[2, 2, 4],
       [2, 3, 3],
       [4, 2, 3]])

In [79]:
arr1 - arr2

array([[ 0,  0,  0],
       [ 0, -1,  1],
       [ 0,  0,  1]])

In [81]:
arr1 * arr2  # this is element wise multiplication and NOT matrix multiplication (or dot product)

array([[1, 1, 4],
       [1, 2, 2],
       [4, 1, 2]])

In [82]:
arr1

array([[1, 1, 2],
       [1, 1, 2],
       [2, 1, 2]])

In [83]:
arr2

array([[1, 1, 2],
       [1, 2, 1],
       [2, 1, 1]])

In [84]:
arr1 @ arr2  # this is matrix multiplication or dot product

array([[6, 5, 5],
       [6, 5, 5],
       [7, 6, 7]])

In [85]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [1. , 0.5, 2. ],
       [1. , 1. , 2. ]])

In [86]:
arr1/0

/tmp/ipykernel_1570/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

### Numpy – Broadcasting.

In [87]:
arr = np.zeros((3,4))

In [88]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [90]:
a = np.array([1,2,3,4])

In [91]:
a

array([1, 2, 3, 4])

In [92]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [93]:
b = np.array([[3,4,5]])

In [94]:
arr1 = arr + b.T

In [95]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [96]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [97]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [98]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [99]:
np.min(arr1)

3.0

In [100]:
np.max(arr1)

5.0