# NumPy - Part - 4

In [1]:
import numpy as np

### Sort, Search & Counting Functions.

In [2]:
arr = np.array([4,2,8,5,3,9,12,56])

In [3]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [4]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [6]:
np.searchsorted(arr,6)  # Find indices where elements should be inserted to maintain sorted order.

5

In [7]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [8]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [9]:
np.count_nonzero(arr1)

6

In [11]:
np.where(arr1 > 0) # returns index for array 1 where elements are greater than zero

(array([1, 2, 3, 4, 5, 9]),)

In [12]:
np.extract(arr1 > 2, arr1)  
# Return the elements of an array arr1 that satisfy arr1 > 2 condition.
# i.e returns elemets of arr1 which are greater than 2

array([324, 645,  65,   6,   6, 234])

### Numpy - Byte Swapping.

In [13]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [16]:
arr.byteswap(True) 
# Swap the bytes of the array elements
# i.e returns memory byte size/address/location of array element or vice-versa

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [17]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [18]:
arr.byteswap(True) 

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [19]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

### Numpy - Copies & Views.

In [20]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [21]:
a = np.copy(arr1)  # deep copy

In [22]:
arr1[0] = 10

In [23]:
arr1

array([ 10, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [24]:
a

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [32]:
b = arr1.view()  # same as b = arr1

# sollow copy
# equivalent to b = arr1

In [26]:
b

array([ 10, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [29]:
arr1[0] = 0

In [30]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [31]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

### Numpy - Matrix Library. - matlib

In [33]:
import numpy.matlib as nm

In [34]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [35]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [36]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Numpy - Linear Algebra

In [39]:
arr1 = np.random.randint([[2,3] , [4,5]])
arr2 = np.random.randint([[5,3] , [2,5]])

In [40]:
arr1

array([[0, 2],
       [0, 0]])

In [41]:
arr2

array([[4, 2],
       [1, 3]])

In [43]:
np.dot(arr1, arr2)  # same as matrix multiplication

array([[2, 6],
       [0, 0]])

In [44]:
arr1 @ arr2

array([[2, 6],
       [0, 0]])