# Feb 26' 23 - NumPy Part-1

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

### creation on Array

In [3]:
# to create a numpy array 
# 1. np.array()
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [7]:
# to create a numpy array 
# 2. np.asarray()
np.asarray(l)

array([1, 2, 3, 4, 5])

In [8]:
type(np.asarray(l))

numpy.ndarray

In [9]:
# creating two dimensional array
arr1 = np.array([[1,2,3] , [2,3,4]])

In [10]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [11]:
# to check the array dimensions
arr.ndim

1

In [12]:
arr1.ndim

2

In [15]:
# creating a matrix
# matrix is subclass of array class
# matrix is one of the type of array
mat = np.matrix(l)

In [16]:
mat

matrix([[1, 2, 3, 4, 5]])

In [18]:
# asanyarray() - covert an input to array type only if the input is not already an array or any array subtype (e.g matrix)
np.asanyarray(l) # passing list variable as an arguement will convert it to array

array([1, 2, 3, 4, 5])

In [19]:
np.asanyarray(mat) # passing an array or its subtype is not going to change anything

matrix([[1, 2, 3, 4, 5]])

### Deep Copy and Sollow Copy

In [23]:
a = arr  # sollow copy

# In cas of sollow copy no new memory location/address is created
# both the variable points to same address
# so if chnage is made to the value stored in that location
# the change will get reflect for both the variables pointing to that address

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
a

array([1, 2, 3, 4, 5])

In [24]:
arr[0] = 100

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
a

array([100,   2,   3,   4,   5])

In [27]:
b = np.copy(arr) # deep copy

# In cas of deep copy a new memory location/address is created
# both the variable points to different address
# so if chnage is made in one variable stored at a location
# that change will NOT get reflect other variables 
# as both variables are pointing to different location/address

In [28]:
arr

array([100,   2,   3,   4,   5])

In [29]:
b

array([100,   2,   3,   4,   5])

In [30]:
b[0] = 234

In [31]:
b

array([234,   2,   3,   4,   5])

In [32]:
arr

array([100,   2,   3,   4,   5])

### Generating an Array

In [35]:
# np.fromfuntion() takes a function as arguement and generates an array
np.fromfunction(lambda i,j : i==j, (3,3))

# i=0,1,2 for (3,3) array
# j=0,1,2 for (3,3) array
# so when i==j i.e 0==0, 1==1, 2==2, it will return True
# for everything else it returns False

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [36]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [45]:
iterable = (i*i for i in range(5))

In [46]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [49]:
iterable = (i*i for i in range(5))

In [50]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [51]:
np.fromstring("23 45 56", sep = " ")

array([23., 45., 56.])

In [52]:
np.fromstring("23,45,56", sep = ",")

array([23., 45., 56.])

### dimension, size and shape of array

In [53]:
arr

array([100,   2,   3,   4,   5])

In [54]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [55]:
arr.ndim

1

In [56]:
arr1.ndim

2

In [59]:
arr.size # gives total elemets inside array

5

In [60]:
arr1.size

6

In [61]:
arr.shape

(5,)

In [63]:
arr1.shape # gives total rows and total columns in an array

(2, 3)

### array datatype

In [64]:
arr.dtype

dtype('int64')

In [65]:
arr1.dtype

dtype('int64')