# NumPy - Part - 3

In [1]:
import numpy as np

### Numpy - Array Manipulation.

In [2]:
arr = np.random.randint(1,10 , (4,4))

In [3]:
arr

array([[4, 8, 3, 3],
       [2, 5, 2, 9],
       [3, 5, 3, 6],
       [5, 9, 2, 6]])

In [4]:
arr.reshape(8,2)

array([[4, 8],
       [3, 3],
       [2, 5],
       [2, 9],
       [3, 5],
       [3, 6],
       [5, 9],
       [2, 6]])

In [5]:
arr

array([[4, 8, 3, 3],
       [2, 5, 2, 9],
       [3, 5, 3, 6],
       [5, 9, 2, 6]])

In [6]:
arr.T

array([[4, 2, 3, 5],
       [8, 5, 5, 9],
       [3, 2, 3, 2],
       [3, 9, 6, 6]])

In [8]:
arr.transpose()

array([[4, 2, 3, 5],
       [8, 5, 5, 9],
       [3, 2, 3, 2],
       [3, 9, 6, 6]])

In [13]:
arr.flatten() # converts multidimensional array into 1-dimensional

array([4, 8, 3, 3, 2, 5, 2, 9, 3, 5, 3, 6, 5, 9, 2, 6])

In [10]:
arr

array([[4, 8, 3, 3],
       [2, 5, 2, 9],
       [3, 5, 3, 6],
       [5, 9, 2, 6]])

In [16]:
np.expand_dims(arr, axis=1) # add one more axis dimension to array

# Insert a new axis that will appear at the `axis` position in the expanded array shape.

array([[[4, 8, 3, 3]],

       [[2, 5, 2, 9]],

       [[3, 5, 3, 6]],

       [[5, 9, 2, 6]]])

In [17]:
np.expand_dims(arr, axis=0) # adds one more dimension to array

# Insert a new axis that will appear at the `axis` position in the expanded array shape.

array([[[4, 8, 3, 3],
        [2, 5, 2, 9],
        [3, 5, 3, 6],
        [5, 9, 2, 6]]])

In [18]:
data = np.array([[1] , [2] , [3]])

In [19]:
data

array([[1],
       [2],
       [3]])

In [21]:
np.squeeze(data)  # Remove axes of length one from `a`.

# basically converting into single dimension array

array([1, 2, 3])

In [23]:
np.repeat(data, 4) # repeat the elements of array by no. of times mentioned

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [25]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [26]:
np.diag(np.array([1,2,3,4]))  # Extract a diagonal or construct a diagonal array.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Numpy - Binary Operators.

In [27]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [28]:
arr1

array([[1, 5, 5, 9],
       [5, 9, 5, 3],
       [5, 1, 9, 9]])

In [29]:
arr2

array([[1, 4, 1, 4],
       [4, 6, 6, 2],
       [6, 6, 6, 3]])

In [32]:
arr1 + arr2 # # element wise addition

array([[ 2,  9,  6, 13],
       [ 9, 15, 11,  5],
       [11,  7, 15, 12]])

In [33]:
arr1*arr2  # element wise multiplication

array([[ 1, 20,  5, 36],
       [20, 54, 30,  6],
       [30,  6, 54, 27]])

In [34]:
arr1 / arr2  # element wise division

array([[1.        , 1.25      , 5.        , 2.25      ],
       [1.25      , 1.5       , 0.83333333, 1.5       ],
       [0.83333333, 0.16666667, 1.5       , 3.        ]])

In [35]:
arr1 - arr2 # element wise substraction

array([[ 0,  1,  4,  5],
       [ 1,  3, -1,  1],
       [-1, -5,  3,  6]])

In [36]:
arr1 ** arr2  # element wise rise to power

array([[     1,    625,      5,   6561],
       [   625, 531441,  15625,      9],
       [ 15625,      1, 531441,    729]])

In [39]:
# bitwise negation
~arr1

array([[ -2,  -6,  -6, -10],
       [ -6, -10,  -6,  -4],
       [ -6,  -2, -10, -10]])

In [38]:
arr1

array([[1, 5, 5, 9],
       [5, 9, 5, 3],
       [5, 1, 9, 9]])

In [40]:
arr1 > arr2

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

### Numpy - String Functions.

In [41]:
arr = np.array(["sudh" , "kumar"])

In [42]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [43]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [44]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [45]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

### Numpy - Mathematical Functions.

In [46]:
arr1

array([[1, 5, 5, 9],
       [5, 9, 5, 3],
       [5, 1, 9, 9]])

In [47]:
np.sin(arr1)

array([[ 0.84147098, -0.95892427, -0.95892427,  0.41211849],
       [-0.95892427,  0.41211849, -0.95892427,  0.14112001],
       [-0.95892427,  0.84147098,  0.41211849,  0.41211849]])

In [48]:
np.cos(arr1)

array([[ 0.54030231,  0.28366219,  0.28366219, -0.91113026],
       [ 0.28366219, -0.91113026,  0.28366219, -0.9899925 ],
       [ 0.28366219,  0.54030231, -0.91113026, -0.91113026]])

In [49]:
np.tan(arr1)

array([[ 1.55740772, -3.38051501, -3.38051501, -0.45231566],
       [-3.38051501, -0.45231566, -3.38051501, -0.14254654],
       [-3.38051501,  1.55740772, -0.45231566, -0.45231566]])

In [50]:
np.log10(arr1)

array([[0.        , 0.69897   , 0.69897   , 0.95424251],
       [0.69897   , 0.95424251, 0.69897   , 0.47712125],
       [0.69897   , 0.        , 0.95424251, 0.95424251]])

In [51]:
np.exp(arr1)

array([[2.71828183e+00, 1.48413159e+02, 1.48413159e+02, 8.10308393e+03],
       [1.48413159e+02, 8.10308393e+03, 1.48413159e+02, 2.00855369e+01],
       [1.48413159e+02, 2.71828183e+00, 8.10308393e+03, 8.10308393e+03]])

In [52]:
np.power(arr1, 2)

array([[ 1, 25, 25, 81],
       [25, 81, 25,  9],
       [25,  1, 81, 81]])

In [53]:
np.mean(arr1)

5.5

In [54]:
np.median(arr1)

5.0

In [55]:
np.std(arr1)

2.8431203515386634

In [56]:
np.var(arr1)

8.083333333333334

In [57]:
np.min(arr1)

1

In [58]:
np.max(arr1)

9

### #Numpy - Arithmetic Operations.

In [59]:
arr1

array([[1, 5, 5, 9],
       [5, 9, 5, 3],
       [5, 1, 9, 9]])

In [60]:
arr2

array([[1, 4, 1, 4],
       [4, 6, 6, 2],
       [6, 6, 6, 3]])

In [61]:
arr1 - arr2

array([[ 0,  1,  4,  5],
       [ 1,  3, -1,  1],
       [-1, -5,  3,  6]])

In [62]:
np.subtract(arr1, arr2)

array([[ 0,  1,  4,  5],
       [ 1,  3, -1,  1],
       [-1, -5,  3,  6]])

In [63]:
np.multiply(arr1, arr2)

array([[ 1, 20,  5, 36],
       [20, 54, 30,  6],
       [30,  6, 54, 27]])

In [64]:
np.mod(arr1, arr2)

array([[0, 1, 0, 1],
       [1, 3, 5, 1],
       [5, 1, 3, 0]])

In [65]:
np.power(arr1, arr2)

array([[     1,    625,      5,   6561],
       [   625, 531441,  15625,      9],
       [ 15625,      1, 531441,    729]])

In [66]:
np.sqrt(arr1)

array([[1.        , 2.23606798, 2.23606798, 3.        ],
       [2.23606798, 3.        , 2.23606798, 1.73205081],
       [2.23606798, 1.        , 3.        , 3.        ]])

### Numpy - Statistical Functions.

In [67]:
arr1

array([[1, 5, 5, 9],
       [5, 9, 5, 3],
       [5, 1, 9, 9]])

In [68]:
np.mean(arr1)

5.5

In [69]:
np.std(arr1)

2.8431203515386634

In [70]:
np.median(arr1)

5.0